name: main

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'dependabot/**'
    tags-ignore:
      - v*
  workflow_dispatch:

jobs:
  prerequisites:
    uses: pulumiverse/infra/.github/workflows/provider-prerequisites.yaml@actions-workflows-v0.0.1
    with:
      provider: heroku
  build:
    needs: prerequisites
    uses: pulumiverse/infra/.github/workflows/provider-build-sdk.yaml@actions-workflows-v0.0.1
    with:
      provider: heroku
